version: '3.8'

services:

  # Serveur NGINX
  nginx-service:
    container_name: nginx-container
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-service
      - database-service

  # Langage PHP 8
  php-service:
    container_name: php-container
    build:
      context: ./php
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/symfony_docker:cached
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - database-service

  # Base de données MySQL 8
  database-service:
    container_name: database-container
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_docker
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql

  # Gestion de base de données phpMyAdmin
  phpmyadmin-service:
    container_name: phpmyadmin-container
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: database-container
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: secret
    restart: always
