api_platform:
  mapping:
    paths: ['%kernel.project_dir%/src/Entity']
  metadata_backward_compatibility_layer: false
  patch_formats:
    json: ['application/merge-patch+json']
  swagger:
    versions: [3]
  show_webby: false
  defaults:
    pagination_enabled: false
